version: '1.0'

services:
  mongo:
    image: 'mongo'
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongovol:/data/db
  weather:
    image: 'gerardc98/nosql-4-weather'
    container_name: weather
volumes:
  mongovol:
    driver: local
